# Generated by Django 4.1.3 on 2022-11-20 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Fuel type',
                'verbose_name_plural': 'Fuels types',
            },
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('deleted_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('capacity', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_type', models.ManyToManyField(to='transport_units.fueltype')),
            ],
            options={
                'verbose_name': 'Transport type',
                'verbose_name_plural': 'Transports Types',
            },
        ),
        migrations.CreateModel(
            name='TransportUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('deleted_date', models.DateField(auto_now=True)),
                ('unit_id', models.IntegerField(unique=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('plate', models.CharField(max_length=50, unique=True)),
                ('last_maintenance_date', models.DateField()),
                ('transport_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_units.transporttype')),
            ],
            options={
                'verbose_name': 'Transport Unit',
                'verbose_name_plural': 'Transports Units',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTransportUnit',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True)),
                ('created_date', models.DateField(blank=True, editable=False)),
                ('modified_date', models.DateField(blank=True, editable=False)),
                ('deleted_date', models.DateField(blank=True, editable=False)),
                ('unit_id', models.IntegerField(db_index=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('plate', models.CharField(db_index=True, max_length=50)),
                ('last_maintenance_date', models.DateField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transport_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transport_units.transporttype')),
            ],
            options={
                'verbose_name': 'historical Transport Unit',
                'verbose_name_plural': 'historical Transports Units',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTransportType',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True)),
                ('created_date', models.DateField(blank=True, editable=False)),
                ('modified_date', models.DateField(blank=True, editable=False)),
                ('deleted_date', models.DateField(blank=True, editable=False)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('capacity', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Transport type',
                'verbose_name_plural': 'historical Transports Types',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
