# Generated by Django 4.1.3 on 2022-11-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransportunit',
            name='last_maintenance_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='transportunit',
            name='last_maintenance_date',
            field=models.DateField(null=True),
        ),
    ]
